#!/usr/bin/python
# Works on python2.7 and python3.5,older version may work,too.

import os            

print("* Building fbs into './gen' ...")

fbsList = []

sep = os.sep

for dirpath, dirs, files in os.walk("."):
    for f in files:
        name,suffix = os.path.splitext(f)
        if suffix == ".fbs":
            cmd = 'flatc -c -o ".' + sep + 'gen' + sep + dirpath.replace("." + sep,"") + '" "' + dirpath + sep + f + '"'
            print(cmd)
            os.system(cmd)
            fbsList.append(dirpath + sep + f)

print("* Generating 'protocol.h' ...")
out = open('./gen/protocol.h','w')
out.write("""
// A part of NEWorld,a free game with similar game rules to Minecraft
// Automatically generated by make_fb.py
// DO NOT MODIFY!

namespace Protocol
{
""")
for f in fbsList:
    out.write("#include \"" + f + "_generated.h\"\n")
out.write("}\n")
out.close()
print("* Done.")
