#!/usr/bin/python
# Works on python2.7 and python3.5,older version may work,too.

import os           
import sys 

print("* Building fbs into './gen' ...")

fbsList = []

sep = os.sep

flatc_path=sys.argv[1] if len(sys.argv)==2 else ""

for dirpath, dirs, files in os.walk("."):
    for f in files:
        name,suffix = os.path.splitext(f)
        if suffix == ".fbs":
            cmd = flatc_path + 'flatc -c -o ".' + sep + 'gen' + sep + dirpath.replace("." + sep,"") + '" "' + dirpath + sep + f + '"'
            print(cmd)
            os.system(cmd)
            fbsList.append(dirpath + sep + f)

print("* Generating 'protocol.h' ...")
if not os.path.exists('./gen/'): os.mkdir('./gen/')
out = open('./gen/protocol.h','w')
out.write("""
// A part of NEWorld, a free game with similar game rules to Minecraft
// Automatically generated by make_fb.py
// DO NOT MODIFY!

""")
for f in fbsList:
    out.write("#include \"" + f.replace(".fbs","") + "_generated.h\"\n")
out.write("\n")
out.close()
print("* Done.")
